### ISSUE TITLE
Highlighting?

### ISSUE THREAD

**Issue by chris-hailstorm** [textmate/unicode.tmbundle#4]
The readme file says the bundle provides "highlighting of non-ASCII characters".

How is that used?  It's not obvious from the menu commands

**Comment by Bibiko** [comment]
This feature has to be used via setting the language grammar for the current document. If you want to know how it works simply open it in the bundle editor and look into "Language Grammars".  It marks non-ASCII characters as "invalid" - if you're using the theme "Mac classic" then all non-ASCII characters should habe a red background and a white foreground colour. 
All these features are a kind of workarounds, e.g. I implemented them actually for my purposes only ;)
