### ISSUE TITLE
Support for Unicode 10.0 / latest standards?

### ISSUE THREAD

**Issue by ytrepus** [textmate/unicode.tmbundle#5]
Hello, 

I'm new to TextMate and really like this Unicode bundle.  Is it possible to update to Unicode 10.0?  (Particularly I would like support for a few characters that are in 8.0.)  Is there an easy way for me to update directly?  Or for the bundle to always pull the latest standard?

Thank you!
Rob

**Comment by Bibiko** [comment]
Hi Rob, good point! I'll update the bundle to the latest Unicode version as soon as possible.

Cheers, Hans

**Comment by ytrepus** [comment]
Great news, thanks Hans!  Let me know if there's anything I can do to help.

**Comment by Bibiko** [comment]
I updated to version 10.0

**Comment by infininight** [comment]
@ytrepus And I just deployed this change, your bundle will update automatically within a few hours.
